version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root