version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
      - echo hello world
      - touch lol
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
